baseURL = "https://CollaboraOnline.github.io"
RelativeURLs=true
CanonifyURLs=true
title = "Collabora Online - Community Page"
copyright = "Unless a license is otherwise specified, content is under CC-BY-SA 3.0"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
	[[menu.main]]
    identifier = "downloads"
    name = "Downloads"
    url = "https://www.collaboraoffice.com/code/"
    weight = 0
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  Subtitle= "CODE"
  author = "Collabora"
  description = "Collabora Online Development Edition"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["buttons.css", "anim.css", "header.css"]
  customJS = []

  [params.social]
    rss = true
    email = "hello@collaboraoffice.com"
    facebook = "https://www.facebook.com/collaboraoffice/"
    twitter = "https://twitter.com/CollaboraOffice"
    linkedin = "https://www.linkedin.com/company/collabora-productivity-ltd/"
    github = "https://github.com/CollaboraOnline/online"
    reddit = "https://www.reddit.com/r/CollaboraOnline/"
    mastodon = "https://mastodon.social/@CollaboraOffice"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
